#! /bin/sh

# Init polybar
bash $HOME/.config/polybar/launch.sh

# Init sxhkd
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

# Set background
# Normal -> feh --bg-scale $HOME/wallpaper.jpg
feh --bg-scale $HOME/christmans_wallpaperflare.jpg
# Picom
picom &

# Normal cursor
xsetroot -cursor_name left_ptr &

#Set workspaces names
bspc monitor -d "" "" "" "" ""

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
